from setuptools import setup, Extension
from Cython.Build import cythonize
import os

# Path to your w64devkit / include if needed
include_path = "C:\\John_Wood\\Applications\\w64devkit\\include"

ext = Extension(
    "kvdb",
    sources=["kvdb.pyx"],  # kvdb.c generated by Cython
    include_dirs=[
        ".",                  # current folder for kvdb.h, global.h, typeflags.h
        include_path,
    ],
    library_dirs=[
        ".",  # current folder where libkvdb.dll.a is
    ],
    libraries=["kvdb"],  # links against libkvdb.dll.a
)

setup(
    name="kvdb",
    ext_modules=cythonize(ext),
)
